### ISSUE TITLE
Ledger still working?

### ISSUE THREAD

**Issue by freekvh** [va1entin/nixos-config#1]
Hi @va1entin ,

It seems like you are the only person in the world who got the Ledger to work on Nixos. I have a Ledger Nano S plus. I tried your udev rules, no luck. I also noticed that the Nano S plus is not specifically mentioned in https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh

Any advice?

Maybe just Ubuntu in a VM...

**Comment by freekvh** [comment]
I can confirm it works on Arch linux after setting their udev rules so it's something with Nix, or I need to take their latest version of their rules and translate it to a .nix config, as you have done.

**Comment by freekvh** [comment]
I got it to work, one only has to add `hardware.ledger.enable = true;` to configuration.nix and the ledger udev rules are automatically created. Then latest app image from ledger works for me (using `appimage-run`).

**Comment by va1entin** [comment]
Hi @freekvh, thanks for your input and investigation. I'm glad you got it to work as I wouldn't be of much help because I've switched from NixOS to Arch/pacman a few years ago. I have updated the README and archived this repo to reflect this.
